// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5buzbNJp1rj5ekUEtLUrJMGVynNN0YYw',
    appId: '1:131650851534:web:b34185cbd5e6ae947f369f',
    messagingSenderId: '131650851534',
    projectId: 'unimentor-3ffe3',
    authDomain: 'unimentor-3ffe3.firebaseapp.com',
    storageBucket: 'unimentor-3ffe3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYVYLE5waX8wqIqOnlnRFV06jCiyCFDKY',
    appId: '1:131650851534:android:4dfa0017a7b11b4b7f369f',
    messagingSenderId: '131650851534',
    projectId: 'unimentor-3ffe3',
    storageBucket: 'unimentor-3ffe3.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5buzbNJp1rj5ekUEtLUrJMGVynNN0YYw',
    appId: '1:131650851534:web:f2949bb2a01bb9847f369f',
    messagingSenderId: '131650851534',
    projectId: 'unimentor-3ffe3',
    authDomain: 'unimentor-3ffe3.firebaseapp.com',
    storageBucket: 'unimentor-3ffe3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrSrfcr7PbQoPvzSTM8Z7db0gQ36x9WiI',
    appId: '1:131650851534:ios:8bdd9221b5360bcc7f369f',
    messagingSenderId: '131650851534',
    projectId: 'unimentor-3ffe3',
    storageBucket: 'unimentor-3ffe3.firebasestorage.app',
    iosBundleId: 'com.example.unimentor',
  );
}